### ISSUE TITLE
Isort version is not optional if setting `requirementsFiles`

### ISSUE THREAD

**Issue by YPCrumble** [isort/isort-action#10]
Thank you so much for building this! As so many people are migrating from TravisCI to GH Actions right now this is a huge help.

Here's a small bug I identified in the bash script inputs. I could see making a PR forcing named input flags instead of simple positional parameters, but I'm not sure the most elegant solution in bash. Please let me know if I could be helpful in solving this!

If `requirementsFiles` is set but `isortVersion` is unset, this code in `/bin/install-packages` thinks that the requirements file input is actually the isort version:

```
#!/usr/bin/env bash

isort_version=$1
requirements_files=$2
```

**Comment by YPCrumble** [comment]
Actually - my solution would be simply to make the _latest_ version of isort the default for this parameter. Maybe there's an easier way that wouldn't force maintainers to continually update that part of the code, however? I'll add a PR to do that but please feel free to let me know if there's a better solution.

**Comment by jamescurtin** [comment]
Thank you for the issue and PR! To address your last point about always using the latest version:

What if the default value of `isortVersion` was set to `latest` and then we updated [this block](https://github.com/isort/isort-action/blob/509a204f78439c470baecc93d845dc27ffba4905/bin/install_packages#L6) to do a string comparison to check for that value? That way, future PRs wouldn't be necessary to update the default version.

**Comment by mgasner** [comment]
Also hit this -- any chance that the linked PR could merge?

**Comment by jamescurtin** [comment]
All set!
