### ISSUE TITLE
How to exclude specific path?

### ISSUE THREAD

**Issue by LorhanSohaky** [isort/isort-action#30]
I would like not to run isort on the folder generated by alembic

**Comment by jamescurtin** [comment]
`isort` can be configured to skip certain directories ([Documentation link](https://pycqa.github.io/isort/docs/configuration/options.html#skip)). Ideally these settings would be stored in an isort config file in your repository, which would ensure the same configuration options are applied if you run isort locally and if you run it as part of a CI pipeline. Alternatively, though, you can provide specific configuration options [via the plugin](https://github.com/isort/isort-action#configuration).
