### ISSUE TITLE
@v1

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [isort/isort-action#61]
Would it be possible to add a **`v1`** tag?
`v1` → `v1.0.0`

Just like the `v0` tag:
`v0` → `v0.1.0`

![isort](https://user-images.githubusercontent.com/3234522/199441679-a18a5619-4310-4b53-a0f2-911c7506f552.png)

**Comment by jamescurtin** [comment]
All set

**Comment by DimitriPapadopoulos** [comment]
Thanks @jamescurtin!
