### ISSUE TITLE
New release to quench the GitHub deprecation warning for `::set-output`

### ISSUE THREAD

**Issue by fabianegli** [isort/isort-action#62]
GitHub is deprecating the `::save-state` `::set-output` commands and GitHub Actions which are using them now emit a warning.

From https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

The issue has already been fixed in [`master`](https://github.com/isort/isort-action/commit/cad8d89379c2bacf535f8ba4e82ef33da20a644a).

The isort-action always throws the following warning now

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

and a release would quench it.

Is the next release already scheduled? Are there specific pending tasks the community could help with for the next release? I'd be glad to help.

**Comment by jamescurtin** [comment]
Should be all set. `v1.1.0` has been released, and the `v1` tag has been updated accordingly.

**Comment by fabianegli** [comment]
Thank you! 💐
