### ISSUE TITLE
No verbosity at all for succesful checks

### ISSUE THREAD

**Issue by niemiaszek** [isort/isort-action#72]
I tried to setup linting workflow using this action and it obviously works as intended, but it lacks any verbosity, even with --verbose option.

I'd expect successful workflow to output something similar to [black formatter action](https://github.com/marketplace/actions/run-black-formatter), but there is none. Such example can be seen in [this **succesful check**](https://github.com/knr-auv/jetson/actions/runs/3735479802) of mine. Verbosity for **failed check** exists, but I'd say it's also unsatisfying. Example in [this failed check](https://github.com/knr-auv/jetson/actions/runs/3735588884/jobs/6339005818) of mine.

Output of checks drastically differs from the one directly ran from isort cli.

**Comment by mf-maymay** [comment]
Came here to report this same issue, but with emphasis on the output for failed checks.

The command line output is informative, showing exactly which imports are problematic.
However, the output from this action only shows which files have poorly-sorted imports.

**Comment by elliot-100** [comment]
Agree. The docs say that the default option is equivalent to `isort . --check-only --diff' but I don't find that to be the case.

@niemiaszek your links don't work for me. Maybe add extract of output here?

I think I will add a new issue for my specific case, as it's not necessarily the same as yours.

**Comment by niemiaszek** [comment]
> @niemiaszek your links don't work for me. Maybe add extract of output here?

You're right, these links stopped working, as Github Actions runs have expiration date. Sorry for that, but it's been 1.5 year and I hoped to resolve this issue a bit faster.

I stopped using this action so I won't be able to help. Last time I used isort in actions was with just using CLI to avoid mentioned issues. Currently I fully use Ruff for [formatting](https://github.com/astral-sh/ruff) and linting, with import sorting option (replacement for _black_ formatter and _isort_, with small differences).

Looks like they're getting official Action support, where you could use CLI with great success.

**Comment by elliot-100** [comment]
Thanks @niemiaszek, no problem. I have moved to `ruff format` instead of isort + black for my own projects, but found/remembered this issue while troubleshooting an existing project. Will try isort CLI for now.
