### ISSUE TITLE
ensure_python: No such file or directory

### ISSUE THREAD

**Issue by PierreMarchand20** [isort/isort-action#80]
I have the following error using a custom docker container for my CI:

```
/home/runner/work/_actions/isort/isort-action/master/bin/ensure_python: No such file or directory
```

see https://github.com/PierreMarchand20/asciinema_automation/actions/runs/5230024092/jobs/9443350726 

Any idea why ? I have no idea how to debug this issue.

**Comment by PierreMarchand20** [comment]
may be related to https://github.com/actions/runner/issues/716 ?

**Comment by jamescurtin** [comment]
Would you be able to test with the branch `fix-80` and confirm that the Github action path is set properly? If it works, I'll merge in the associated PR.

**Comment by PierreMarchand20** [comment]
It fixes the call to `ensure_python`, but another error appears in `run_isort`: https://github.com/PierreMarchand20/asciinema_automation/actions/runs/5244183045/jobs/9469827688

**Comment by PierreMarchand20** [comment]
There is an error in the installation of isort apparently : `/opt/hostedtoolcache/Python/3.11.3/x64/bin/python: bad interpreter: No such file or directory`

**Comment by PierreMarchand20** [comment]
I see you call directly `pip` and `pip3` in `https://github.com/isort/isort-action/blob/master/bin/install_packages`, it may be more robust to call `python -m pip` from what I understood.
